GET http://localhost:8000/mascotas/buscar HTTP/1.1

###
POST http://localhost:8000/mascotas/crear HTTP/1.1
Content-Type: application/json

{
    "nombre": "Toby",
    "edad": 5
}

###
GET http://localhost:8000/mascotas/buscarId/1 HTTP/1.1

###
PUT http://localhost:8000/mascotas/actualizar/1 HTTP/1.1
Content-Type: application/json

{
    "nombre":"Guardian"
}

###
DELETE http://localhost:8000/mascotas/eliminar/3 HTTP/1.1

###
DELETE http://localhost:8000/mascotas/eliminarTodo HTTP/1.1