GET http://localhost:8000/mascotas/buscar HTTP/1.1

###
POST http://localhost:8000/mascotas/crear HTTP/1.1
Content-Type: application/json

{
    "nombre": "Princesa",
    "edad": 4
}

###
GET http://localhost:8000/mascotas/buscarId/6 HTTP/1.1

###
PUT http://localhost:8000/mascotas/actualizar/6 HTTP/1.1
Content-Type: application/json

{
    "nombre":"Max",
    "edad":10
}

###
DELETE http://localhost:8000/mascotas/eliminar/3 HTTP/1.1

###
DELETE http://localhost:8000/mascotas/eliminarTodo HTTP/1.1